### ISSUE TITLE
Latest process_waveform_analysis.py not working

### ISSUE THREAD

**Issue by ABlairJamieson** [WCTE/T9BeamTestAna#16]
The last commit seems to be missing lines that initialize pedestals, pedestal_sigmas,... in process_waveforms function.

It works with prior to the last commit that doesn't have these arrays.

**Comment by nickwp** [comment]
This was caused by a merge error in Alie's PR that was mistakenly included. It was fixed (and several other changes to update to run on the hodoscope runs etc) but that apparently never got merged. I've opened a new PR to merge all those changes.

**Comment by nickwp** [comment]
See #17 for the PR with the version that should be used.

**Comment by ABlairJamieson** [comment]
Ok. That should resolve the issue.
